CREATE TABLE PRODUCT (
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(5000)
);

CREATE TABLE REVIEW (
    REVIEW_ID INT NOT NULL  AUTO_INCREMENT PRIMARY KEY ,
    TITLE VARCHAR(255) NOT NULL ,
    DESCRIPTION VARCHAR(5000) ,
    UP_VOTE INT,
    DOWN_VOTE INT,
    PRODUCT_ID INT NOT NULL,
    CONSTRAINT FK_PRODUCT_REVIEW FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE COMMENT (
    COMMENT_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    COMMENT_TEXT VARCHAR(5000) ,
    REVIEW_ID INT NOT NULL ,
    CONSTRAINT FK_COMMENT_REVIEW FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW(REVIEW_ID)
);
